#!/usr/bin/env bash
# Rescue useful data from yoga's eMMC mounted at /mnt.
#
# Surveys what's there, prints sizes for the salvageable categories,
# asks for confirmation, then packs everything worth keeping into a
# single zstd-compressed tarball.
#
# What gets saved (relative to /mnt):
#   /home                       -- user dotfiles, projects, anything they put there
#   /root                       -- root's shell history, ssh, etc
#   /etc/ssh/ssh_host_*_key*    -- host SSH identity (in case we want to re-adopt it)
#   /etc/machine-id             -- systemd identity, sometimes useful
#   /etc/nixos                  -- *if* present and not symlink-to-empty
#   /var/lib/iwd                -- wifi profiles, if NetworkManager isn't in use
#   /var/lib/NetworkManager     -- if it is
#   /var/lib/bluetooth          -- paired device keys
#   /var/lib/systemd/random-seed -- not strictly necessary, but harmless
#   /var/lib/tailscale          -- if installed
#   /var/lib/postgresql, /var/lib/mysql -- DBs (warn before tarring; size matters)
#   /var/lib/docker, /var/lib/containers -- if present (warn -- often huge)
#   /var/spool/cron             -- crontabs
#   /var/log/journal/<id>       -- last journal; useful for diagnosing F-1
#
# What's deliberately SKIPPED:
#   /nix/                       -- rebuilds; no point in copying
#   /var/cache/, /var/tmp/      -- cache, will regenerate
#   /var/log/* (except journal) -- mostly rotated text logs, low value
#   /tmp                        -- ephemeral
#   /boot                       -- regenerated by nixos-install
#   /var/lib/nixos              -- userid map, will be re-derived
#
# Output format: zstd tarball, default /root/yoga-emmc-rescue.tar.zst.
# Override with OUTPUT=/path/to/file env var.
set -euo pipefail

SRC=/mnt
OUTPUT="${OUTPUT:-/root/yoga-emmc-rescue.tar.zst}"

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
log() { printf '\n=== %s ===\n' "$*"; }
sz()  {
    local p=$1
    if [[ -e $p ]]; then
        sudo du -sh --apparent-size "$p" 2>/dev/null | cut -f1
    else
        echo "-"
    fi
}

[[ -d $SRC ]] || die "$SRC is not a directory. Mount the eMMC at /mnt first."
[[ -d $SRC/etc ]] || die "$SRC/etc missing. Is /mnt really yoga's root filesystem?"

if [[ -e $OUTPUT ]]; then
    die "$OUTPUT already exists. Move or delete it, or set OUTPUT= to a new path."
fi

mkdir -p "$(dirname "$OUTPUT")"

# Items to consider. Each entry: "<relative path under /mnt>"
# In tar's eyes these are relative paths after `-C /mnt`.
CANDIDATES=(
    home
    root
    etc/ssh
    etc/machine-id
    etc/nixos
    var/lib/iwd
    var/lib/NetworkManager
    var/lib/bluetooth
    var/lib/systemd/random-seed
    var/lib/tailscale
    var/lib/postgresql
    var/lib/mysql
    var/lib/docker
    var/lib/containers
    var/spool/cron
    var/log/journal
)

log "Survey of $SRC"
printf '%-32s %s\n' "path (under /mnt)" "size"
printf '%-32s %s\n' "--------------------------------" "----"
INCLUDE=()
for c in "${CANDIDATES[@]}"; do
    full="$SRC/$c"
    if [[ -e $full ]]; then
        SIZE=$(sz "$full")
        printf '%-32s %s\n' "$c" "$SIZE"
        INCLUDE+=("$c")
    fi
done

if [[ ${#INCLUDE[@]} -eq 0 ]]; then
    die "Nothing of interest found under $SRC. Wrong mount?"
fi

log "Total uncompressed size of selected items"
sudo du -sch --apparent-size "${INCLUDE[@]/#/$SRC/}" 2>/dev/null | tail -1

# Warn on big-byte categories
for big in var/lib/docker var/lib/containers var/lib/postgresql var/lib/mysql; do
    if [[ -e "$SRC/$big" ]]; then
        SZB=$(sudo du -sb --apparent-size "$SRC/$big" 2>/dev/null | cut -f1)
        if (( SZB > 500*1024*1024 )); then
            printf '\nWARN: %s is %s — consider excluding (edit script, remove from CANDIDATES).\n' \
                "$big" "$(sz "$SRC/$big")"
        fi
    fi
done

log "Output destination"
echo "  $OUTPUT"
df -h "$(dirname "$OUTPUT")" | tail -1

read -rp "Proceed with archive? [y/N] " ANS
[[ $ANS == [yY] ]] || die "Aborted."

log "Creating archive (this may take a few minutes)"
# --acls --xattrs preserve SELinux contexts / capability bits / etc
# --one-file-system stops descent into any bind-mounts under /mnt
# -P preserves leading / for clarity in archive listing (we're using -C so paths inside are relative anyway)
# zstd -T0 uses all cores
sudo tar \
    --create \
    --acls --xattrs --xattrs-include='*' \
    --numeric-owner \
    --one-file-system \
    --warning=no-file-changed \
    --warning=no-file-removed \
    -C "$SRC" \
    "${INCLUDE[@]}" \
| sudo zstd -T0 -19 -o "$OUTPUT"

log "Done"
sudo chown "$(id -u):$(id -g)" "$OUTPUT" 2>/dev/null || true
ls -lh "$OUTPUT"
echo
echo "Verify with:"
echo "  zstd -d -c '$OUTPUT' | tar -tvf - | head"
echo
echo "Restore home dir later with:"
echo "  cd / && zstd -d -c '$OUTPUT' | sudo tar -xv --acls --xattrs --numeric-owner home"
