(deftheme spencer-dark
  "Created 2021-08-23.")

(custom-theme-set-variables
 'spencer-dark
 '(ansi-color-names-vector ["#ffffff" "#f36c60" "#8bc34a" "#fff59d" "#4dd0e1" "#b39ddb" "#81d4fa" "#263238"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'spencer-dark
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#ff8A65"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#84ffff"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#9ccc65"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#84ffff"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ffcc80"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#f36c60"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#f36c60")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#ff9800")))))
 '(highlight-indentation-face ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 89)) (:background "#1c1f26"))))
 '(flymake-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#ff9800") :background "#263238"))))
 '(flymake-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#f36c60") :background "#263238"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#263238" :background "#8bc34a" :inverse-video nil))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#8bc34a"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#263238" :background "#8bc34a" :inverse-video nil))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#263238" :inherit font-lock-warning-face :inverse-video t))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#f36c60" :background "#263238"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(cursor ((t (:background "#ff9800" :width extra-expanded))))
 '(fringe ((((class color) (min-colors 89)) (:background "#263238"))))
 '(linum ((((class color) (min-colors 89)) (:background "#263238" :foreground "#a7adba"))))
 '(border ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:background "#555555" :foreground "#555555"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#37474f"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#ffffff" :background nil :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#a7adba" :background "#1c1f26" :weight normal :box nil))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#ffffff" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#b39ddb" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(region ((((class color) (min-colors 89)) (:background "#555555"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#bf616a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#b39ddb" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#37474f" :box (:line-width 1 :color "#ffffff")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#81d4fa" :bold t))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#4dd0e1" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#8bc34a" :background "#1c1f26" :extend t))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#8bc34a" :background "#1c1f26"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#80cbc4" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#81d4fa" :height 1.35))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#8bc34a" :height 1.35))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :height 1.35))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#8bc34a" :bold t :background "#1b5e20"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#263238" :background "#263238"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#4dd0e1" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#e3f2fd" :background "#1c1f26"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#ffab91" :bold t :background "#dd2c00"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#f36c60"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#b3e5fc" :background "#1e2930" :box (:style released-button) :extend t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#b3e5fc" :background "#1e2930" :box (:style released-button) :extend t))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit outline-1 :background "#455A64" :weight bold :box (:style released-button) :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit outline-2 :background "#35575b" :box (:style released-button) :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit outline-3 :height 1.1))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit outline-4 :height 1.0))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit outline-5))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit outline-6))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit outline-7))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit outline-8))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#fff59d"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#ff9800"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground nil))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#4dd0e1" :background nil))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#81d4fa" :background nil :slant normal))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#b0bec5" :background "#78909c"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#b0bec5" :background "#78909c"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#F0F0F0"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#C0C0C0"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "#1c1f26" :background "#78909c"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#b0bec5" :background "#78909c"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#37474f"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#eceff1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e1f5fe"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#a5d6a7"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#ffcc80"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b3e5fc"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#111111"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "aquamarine1"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b39ddb"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#ffffff" :weight bold))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#b0bec5" :weight normal))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#81d4fa" :weight normal))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#ff9800" :weight normal))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#b0bec5" :weight normal))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:foreground "#b0bec5" :weight normal))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#b0bec5" :weight normal))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#fff59d" :weight normal))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight normal))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight normal))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#ff9800" :weight normal))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#f36c60" :background nil :weight normal))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-1 :foreground "#b0bec5"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-2 :foreground "#b0bec5"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-3 :foreground "#b0bec5"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-7))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-8))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1 :foreground "#b0bec5"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2 :foreground "#b0bec5"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3 :foreground "#b0bec5"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-4 :foreground "#b0bec5"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-5 :foreground "#b0bec5"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-6 :foreground "#b0bec5"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#263238")))))

(set-face-attribute 'default nil :family "DejaVu Sans Mono" :height 110)
(set-face-attribute 'fixed-pitch nil :family "DejaVu Sans Mono")
(set-face-attribute 'variable-pitch nil :family "DejaVu Sans Mono")
(variable-pitch-mode 1)
(tool-bar-mode 0)

(provide-theme 'spencer-dark)
