
(deftheme spencer
  
  "Created 2021-08-23.")

(custom-theme-set-variables
 'spencer
 '(ansi-color-names-vector ["#212121" "#B71C1C" "#558b2f" "#FFA000" "#2196f3" "#4527A0" "#00796b" "#FAFAFA"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'spencer
 '(set-fontset-font "fontset-default" 'symbol "Noto Color Emoji")
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "magenta"))))
 '(font-lock-comment-face ((t (:foreground "magenta"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#673ab7"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#0097A7"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#00796b"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#4527A0"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#689f38"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#0097A7"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#EF6C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#B71C1C"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#B71C1C")))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:style wave :color "#2196f3")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#FF5722")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#B71C1C" :background "#ECEFF1"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#2196f3" :background "#ECEFF1"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#FFA000" :background "#ECEFF1"))))
 '(highlight-indentation-face ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 89)) (:background "#e0f7fa"))))
 '(flymake-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#FF5722") :background "#FAFAFA"))))
 '(flymake-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#B71C1C") :background "#FAFAFA"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f" :inverse-video nil))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f" :inverse-video nil))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#FAFAFA" :inherit font-lock-warning-face :inverse-video t))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#4527A0"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#B71C1C" :background "#FAFAFA"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(cursor ((t (:background "#FF5722" :width ultra-expanded))))
 '(fringe ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(border ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(vertical-border ((((class color) (min-colors 89)) (:background "#90A4AE" :foreground "#90A4AE"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#ECEFF1"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#212121" :background "#e0f7fa" :box (:line-width 2 :color "#ECEFF1")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#212121" :background nil :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#a7adba" :background "#ECEFF1" :weight normal))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#212121" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#4527A0" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(region ((((class color) (min-colors 89)) (:background "#90A4AE"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#bf616a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#4527A0" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#B71C1C" :inverse-video t :underline nil))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#558b2f" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#ECEFF1" :box (:line-width 1 :color "#212121")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#607d8b" :background "#cfd8dc"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#607d8b" :background "#cfd8dc"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#F0F0F0"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#C0C0C0"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "#607d8b" :background "#cfd8dc"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#607d8b" :background "#cfd8dc"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "#212121" :background "#e0f7fa"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(default ((t (:background "#FAFAFA" :foreground "#212121" :height 110 :family "DejaVu Sans Mono")))))

(set-face-attribute 'default nil :family "DejaVu Sans Mono" :height 110)
(set-face-attribute 'fixed-pitch nil :family "DejaVu Sans Mono")
(set-face-attribute 'variable-pitch nil :family "DejaVu Sans Mono")
(variable-pitch-mode 1)
(tool-bar-mode 0)

(provide-theme 'spencer)
